name: flutter_audio_player
description: A new flutter plugin project.
version: 0.0.1
homepage:
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

flutter:
  plugin:
    platforms:
      windows:
        default_package: flutter_audio_player_windows

dependencies:
  flutter:
    sdk: flutter

#  flutter_audio_player_platform_interface: ^0.0.11
  flutter_audio_player_platform_interface:
    git:
      url: https://github.com/shaozict/flutter_audio_player.git
      path: flutter_audio_player_platform_interface
  flutter_audio_player_windows:
    git:
      url: https://github.com/shaozict/flutter_audio_player.git
      path: flutter_audio_player_windows
#  flutter_audio_player_windows:
#    path: ../flutter_audio_player_windows
  rxdart: ^0.27.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

